version: '3.8'

services:
  admin_client_v1:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"

  admin_server_v1:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

